### ISSUE TITLE
!important is not expanded

### ISSUE THREAD

**Issue by drzraf** [dlanger/inlinestyler#17]
having a css like:
```display: none !important;```
will not add a ```style="display: none !important;"``` attribute to elements.
The ```!imporant``` part is omitted.
But it is useful: https://stackoverflow.com/questions/4013670/gmail-is-ignoring-displaynone

**Comment by dlanger** [comment]
Can you confirm this is still an issue? It seems to work for me:
```python
In [3]: from inlinestyler.utils import inline_css

In [4]: tst = u'<html><head><style>.test_1 { display: none !important; } </style></head><body><p class="test_1">Hello World!</p></body></html>'

In [5]: print inline_css(tst)
<html>
<head></head>
<body><p class="test_1" style="display: none !important">Hello World!</p></body>
</html>

In [6]: print inlinestyler.VERSION
(0, 2, 3)
```

**Comment by drzraf** [comment]
I just retried now, and indeed it works as intended.
I don't know what happened (to me) to get it wrong in the first place.

You can close the bug, very sorry for the noise!
