### ISSUE TITLE
Broken Python3 compatibility

### ISSUE THREAD

**Issue by riklaunim** [dlanger/inlinestyler#20]
Updating from 0.2.1 to 0.2.2 breakes on Python 3.4

    File "/env/lib/python3.4/site-packages/inlinestyler/utils.py", line 17, in inline_css
        converter.perform(document, html_message, '', encoding=encoding)
    File "/env/lib/python3.4/site-packages/inlinestyler/converter.py", line 62, in perform
        self.convertedHTML = etree.tostring(document, method="html", pretty_print=True).encode(encoding)
    AttributeError: 'bytes' object has no attribute 'encode'

**Comment by dlanger** [comment]
Sorry - will revert that bit by midday (and add a Py3 smoke test so I stop doing this).

**Comment by dlanger** [comment]
Released `0.2.3` to PyPi, which gets Python 3 working again - thanks for filing this issue. 

I've also got `tox` running locally so I can run the tests under 3.4 there, and have added 3.4 as a target on Travis to try and stop these at the CI level.
