### ISSUE TITLE
IOError: Too many open files

### ISSUE THREAD

**Issue by kprikshit** [dlanger/inlinestyler#25]
Hi, 
I have been getting the following error:
IOError: Too many open files: '/usr/local/lib/python2.7/dist-packages/inlinestyler/css_compliance.csv'

I was running this in a loop (5000+) and that's when this happened.

**Comment by dlanger** [comment]
I'm betting this is related to how we never `close()` that file [here](https://github.com/dlanger/inlinestyler/blob/27223553328500e1d2ea22b9fc0fc9e2f87657a4/inlinestyler/converter.py#L85) - that line should be in a `with` block as mentioned in the [docs](https://docs.python.org/2/tutorial/inputoutput.html#methods-of-file-objects).

Out of interest, what's your use for running this in a loop?

**Comment by dlanger** [comment]
Changed the file handling a bit in version 0.2.5 to fix what I'm guessing was causing this.

**Comment by kprikshit** [comment]
@dlanger this is due to that not closing the file. `fp.close()` will take care of it. 

Thanks for the prompt reply

**Comment by kprikshit** [comment]
@dlanger We were processing a bunch of emails in the loop. The content was dynamically generated and hence this function needed to be called in each function call.
